version: "3.6"

services:
  mongodb:
    image: "mongo"
    volumes:
      - movies_data:/data/db

  server:
    build: 
      context: .
    depends_on:
      - mongodb
    environment:
      - DB
      - NODE_ENV
      - JWT_SECRET
    ports:
      - "127.0.0.1:5000:3000"
    restart: unless-stopped
    volumes:
      - /var/log/movies-server:/app/logs

volumes:
  movies_data: